param(
  [string]$Tag = $env:GITHUB_REF_NAME,
  [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
  [string]$Output = "src\generated\changelog.ts",
  [switch]$Stdout
)

$ErrorActionPreference = "Stop"

function Escape-TypeScriptTemplate([string]$Value) {
  return $Value.Replace('\', '\\').Replace('`', '\`').Replace('$', '\$')
}

function Invoke-GitOptional {
  param([string[]]$Arguments)

  $oldPreference = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try {
    $result = & git @Arguments 2>$null
    $exitCode = $LASTEXITCODE
    $global:LASTEXITCODE = 0
    if ($exitCode -ne 0) {
      return ""
    }
    return $result
  } finally {
    $ErrorActionPreference = $oldPreference
  }
}

Push-Location $ProjectRoot
try {
  if ([string]::IsNullOrWhiteSpace($Tag)) {
    $Tag = Invoke-GitOptional @("describe", "--tags", "--exact-match")
  }

  $versionTitle = if ([string]::IsNullOrWhiteSpace($Tag)) {
    "Unreleased"
  } else {
    $Tag.Trim()
  }

  # workflow_dispatch can build a release before its tag exists. Keep the
  # requested tag as the heading, but read commits from HEAD in that case.
  $releaseRef = "HEAD"
  $tagExists = $false
  if ($versionTitle -ne "Unreleased") {
    $tagExists = -not [string]::IsNullOrWhiteSpace(
      (Invoke-GitOptional @("rev-parse", "--verify", "--quiet", "refs/tags/$versionTitle"))
    )
    if ($tagExists) {
      $releaseRef = $versionTitle
    }
  }

  $previousTag = ""
  if ($tagExists) {
    $previousTag = Invoke-GitOptional @("describe", "--tags", "--abbrev=0", "--match", "v*", "$versionTitle^")
  } else {
    $previousTag = Invoke-GitOptional @("describe", "--tags", "--abbrev=0", "--match", "v*", $releaseRef)
  }

  $range = if (-not [string]::IsNullOrWhiteSpace($previousTag)) {
    "$previousTag..$releaseRef"
  } else {
    $releaseRef
  }

  $commits = @(Invoke-GitOptional @("log", $range, "--pretty=format:%s (%h)", "--no-merges"))
  if ($commits.Count -eq 0) {
    $commits = @("(no changes)")
  }

  $date = Get-Date -Format "yyyy-MM-dd"
  $items = $commits | ForEach-Object { "- $_" }
  $changelogTitle = @([char]0x66F4, [char]0x65B0, [char]0x65E5, [char]0x5FD7) -join ""
  $changesTitle = @([char]0x53D8, [char]0x66F4) -join ""
  $body = "# MaaInspector $changelogTitle`n`n## $versionTitle ($date)`n`n### $changesTitle`n$($items -join "`n")`n"

  $outputPath = Join-Path $ProjectRoot $Output
  $outputDir = Split-Path $outputPath -Parent
  New-Item -ItemType Directory -Path $outputDir -Force | Out-Null

  $escaped = Escape-TypeScriptTemplate $body
  $module = "// This file is generated by scripts/generate-changelog.ps1.`nexport const changelogContent = ``$escaped```n"
  $module | Set-Content -Path $outputPath -Encoding UTF8

  if ($Stdout) {
    Write-Output $body
  } else {
    Write-Host "Generated changelog at $outputPath"
  }
} finally {
  Pop-Location
}
