param(
  [string]$Tag = $env:GITHUB_REF_NAME,
  [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
  [string]$Output = "src\generated\changelog.ts",
  [switch]$Stdout
)

$ErrorActionPreference = "Stop"

function Escape-TypeScriptTemplate([string]$Value) {
  return $Value.Replace('\', '\\').Replace('`', '\`').Replace('$', '\$')
}

function Invoke-GitOptional {
  param([string[]]$Arguments)

  $oldPreference = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try {
    $result = & git @Arguments 2>$null
    $exitCode = $LASTEXITCODE
    $global:LASTEXITCODE = 0
    if ($exitCode -ne 0) {
      return ""
    }
    return $result
  } finally {
    $ErrorActionPreference = $oldPreference
  }
}

function Get-ChangelogSection([string]$Commit) {
  if ($Commit -match '^feat(\([^)]+\))?!?:') {
    return "features"
  }
  if ($Commit -match '^fix(\([^)]+\))?!?:') {
    return "fixes"
  }
  return "improvements"
}

function Group-ChangelogCommits([string[]]$Commits) {
  $groups = [ordered]@{
    features = [System.Collections.Generic.List[string]]::new()
    improvements = [System.Collections.Generic.List[string]]::new()
    fixes = [System.Collections.Generic.List[string]]::new()
  }
  foreach ($commit in $Commits) {
    $groups[(Get-ChangelogSection $commit)].Add($commit)
  }
  return $groups
}

function Format-ChangelogBody {
  param(
    [string]$Version,
    [string]$Date,
    [string[]]$Commits
  )

  $sectionTitles = [ordered]@{
    features = "Features"
    improvements = "Improvements"
    fixes = "Fixes"
  }
  $groupedCommits = Group-ChangelogCommits $Commits

  $bodyLines = [System.Collections.Generic.List[string]]::new()
  $bodyLines.Add("# MaaInspector Changelog")
  $bodyLines.Add("")
  $bodyLines.Add("## $Version ($Date)")
  foreach ($section in $sectionTitles.Keys) {
    if ($groupedCommits[$section].Count -eq 0) {
      continue
    }
    $bodyLines.Add("")
    $bodyLines.Add("### $($sectionTitles[$section])")
    foreach ($commit in $groupedCommits[$section]) {
      $bodyLines.Add("- $commit")
    }
  }

  return ($bodyLines -join "`n") + "`n"
}

function New-ChangelogRelease {
  param(
    [string]$Version,
    [string]$Date,
    [string[]]$Commits
  )

  $groups = Group-ChangelogCommits $Commits
  $sections = @(
    foreach ($kind in @("features", "improvements", "fixes")) {
      if ($groups[$kind].Count -gt 0) {
        [ordered]@{
          kind = $kind
          items = @($groups[$kind])
        }
      }
    }
  )

  return [ordered]@{
    id = $Version.ToLowerInvariant()
    version = $Version
    date = $Date
    sections = $sections
  }
}

Push-Location $ProjectRoot
try {
  if ([string]::IsNullOrWhiteSpace($Tag)) {
    $Tag = Invoke-GitOptional @("describe", "--tags", "--exact-match")
  }

  $versionTitle = if ([string]::IsNullOrWhiteSpace($Tag)) {
    "Unreleased"
  } else {
    $Tag.Trim()
  }

  # workflow_dispatch can build a release before its tag exists. Keep the
  # requested tag as the heading, but read commits from HEAD in that case.
  $releaseRef = "HEAD"
  $tagExists = $false
  if ($versionTitle -ne "Unreleased") {
    $tagExists = -not [string]::IsNullOrWhiteSpace(
      (Invoke-GitOptional @("rev-parse", "--verify", "--quiet", "refs/tags/$versionTitle"))
    )
    if ($tagExists) {
      $releaseRef = $versionTitle
    }
  }

  $previousTag = ""
  if ($tagExists) {
    $previousTag = Invoke-GitOptional @("describe", "--tags", "--abbrev=0", "--match", "v*", "$versionTitle^")
  } else {
    $previousTag = Invoke-GitOptional @("describe", "--tags", "--abbrev=0", "--match", "v*", $releaseRef)
  }

  $range = if (-not [string]::IsNullOrWhiteSpace($previousTag)) {
    "$previousTag..$releaseRef"
  } else {
    $releaseRef
  }

  $commits = @(Invoke-GitOptional @("log", $range, "--pretty=format:%s (%h)", "--no-merges"))
  if ($commits.Count -eq 0) {
    $commits = @("(no changes)")
  }

  $commitDate = Invoke-GitOptional @("show", "-s", "--format=%cs", "${releaseRef}^{commit}")
  $date = if ([string]::IsNullOrWhiteSpace($commitDate)) {
    Get-Date -Format "yyyy-MM-dd"
  } else {
    $commitDate.Trim()
  }
  $body = Format-ChangelogBody -Version $versionTitle -Date $date -Commits $commits
  $release = New-ChangelogRelease -Version $versionTitle -Date $date -Commits $commits

  $outputPath = Join-Path $ProjectRoot $Output
  $outputDir = Split-Path $outputPath -Parent
  New-Item -ItemType Directory -Path $outputDir -Force | Out-Null

  $escaped = Escape-TypeScriptTemplate $body
  $releaseJson = $release | ConvertTo-Json -Depth 8
  $module = @"
// This file is generated by scripts/generate-changelog.ps1.
import type { ChangelogRelease } from '@/features/changelog/types'

export const changelogContent = ``$escaped``
export const changelogReleases = [$releaseJson] satisfies ChangelogRelease[]
"@
  $module | Set-Content -Path $outputPath -Encoding UTF8

  if ($Stdout) {
    Write-Output $body
  } else {
    Write-Host "Generated changelog at $outputPath"
  }
} finally {
  Pop-Location
}
